Remove useless file
omise/omise.js pull request #89
Opened 2020-12-23 04:39 UTC by danfowler

**1. Objective**

This file is useless.  It contains an HTML file instead of the actual library.

**2. Description of change**

Removed useless file.

**3. Quality assurance**

n/a

**4. Operations impact**

n/a

2020-12-24 07:37 UTC, swathi1102 approved these changes

2020-12-24 09:04 UTC, mayurkathale approved these changes
LGTM

2021-03-23 02:49 UTC, asmyshlyaev177 requested changes
It used by `easyXDM`.

2021-03-23 02:52 UTC, danfowler commented
@asmyshlyaev177 OK, please make a plan for removing `easyXDM`

2021-03-23 02:52 UTC, closed without merging